name: 'Run Docker'

description: 'Runs a command inside a Docker container.'

inputs:
  image-url:
    description: 'The tag of the Docker image to run.'
    required: true
  command:
    description: 'The command to run.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Load image url
      id: load_image_url
      shell: bash
      run: |
        IMAGE_URL=`make image-url`
        echo "image-url=$IMAGE_URL" >> "$GITHUB_OUTPUT"
    - name: setup
      shell: bash
      run: |
        echo "Loading cached image: ${{ steps.load_image_url.outputs.image-url }}"
    - name: Cache docker image
      uses: actions/cache@v2
      with:
        path: docker-image.tar
        key: ${{ steps.load_image_url.outputs.image-url }}
    - name: load image
      shell: bash
      run: docker load --input docker-image.tar
    - name: run
      shell: bash
      env:
        NO_IMAGE_BUILD: 1
      run: ${{ inputs.command }}
