name: 'Run Docker'

description: 'Runs a command inside a Docker container.'

inputs:
  image-tag:
    description: 'The tag of the Docker image to run.'
    required: true
  command:
    description: 'The command to run inside the Docker container.'
    required: true

runs:
  using: "composite"
  steps:
    - name: load image
      shell: bash
      run: docker load docker-image.tar
    - name: run
      using: 'docker'
      image: '${{ inputs.image-url }}'
      args:
        - 'sh'
        - '-c'
        - '${{ inputs.command }}'
