version: 2
updates:
  # autogpt_libs (Poetry project)
  - package-ecosystem: "pip"
    directory: "autogpt_platform/autogpt_libs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # backend (Poetry project)
  - package-ecosystem: "pip"
    directory: "autogpt_platform/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # frontend (Next.js project)
  - package-ecosystem: "npm"
    directory: "autogpt_platform/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # infra (Terraform)
  - package-ecosystem: "terraform"
    directory: "autogpt_platform/infra"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # market (Poetry project)
  - package-ecosystem: "pip"
    directory: "autogpt_platform/market"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Docker
  - package-ecosystem: "docker"
    directory: "autogpt_platform/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Submodules
  - package-ecosystem: "gitsubmodule"
    directory: "autogpt_platform/supabase"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
