version: 2
updates:
  # autogpt_libs (Poetry project)
  - package-ecosystem: "pip"
    directory: "autogpt_platform/autogpt_libs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # backend (Poetry project)
  - package-ecosystem: "pip"
    directory: "autogpt_platform/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # frontend (Next.js project)
  - package-ecosystem: "npm"
    directory: "autogpt_platform/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # infra (Terraform)
  - package-ecosystem: "terraform"
    directory: "autogpt_platform/infra"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # market (Poetry project)
  - package-ecosystem: "pip"
    directory: "autogpt_platform/market"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # Docker
  - package-ecosystem: "docker"
    directory: "autogpt_platform/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # Submodules
  - package-ecosystem: "gitsubmodule"
    directory: "autogpt_platform/supabase"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  # Docs
  - package-ecosystem: 'pip'
    directory: "docs/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    target-branch: "dev"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
