AutoGPT Agent:
- changed-files:
  - any-glob-to-any-file: classic/original_autogpt/**

Forge:
- changed-files:
  - any-glob-to-any-file: classic/forge/**

Benchmark:
- changed-files:
  - any-glob-to-any-file: classic/benchmark/**

Frontend:
- changed-files:
  - any-glob-to-any-file: classic/frontend/**

documentation:
- changed-files:
  - any-glob-to-any-file: docs/**

Builder:
- changed-files:
  - any-glob-to-any-file: autogpt_platform/frontend/**

Server:
- changed-files:
  - any-glob-to-any-file: autogpt_platform/backend/**
