version: 0.3.0
configurations:
  - ai_goals:
      - There are files located in the folder ./python_doc/ , I want you to go through them and produce a detailed summary aimed at engineers and save these summaries in files located in the folder ./python_summary
      - Analyze the code in the ./python_doc/ folder and provide suggestions for improvements and optimizations
      - Create a list of frequently asked questions (FAQs) related to the content in the ./python_doc/ folder
    ai_name: PythonGPT
    ai_role: Produce high-quality and well-detailed documentation and tutorial for Python Developers
    command_registry: null
    prompt_generator: null
  - ai_goals:
      - There are files located in the folder ./python_doc/ , I want you to go through them and produce a detailed summary aimed at engineers and save these summaries in files located in the folder ./python_summary
      - Generate a tutorial for beginners based on the content found in the ./python_doc/ folder
      - Identify the most important concepts and create a cheat sheet for developers using the information in the ./python_doc/ folder
    ai_name: PythonGPT2
    ai_role: Produce high-quality and well-detailed documentation and tutorial for Python Developers
    command_registry: null
    prompt_generator: null
  - ai_goals:
      - What is Barrack Obama Birth Date
      - Is the earth flat ?
    ai_name: TestGPT
    ai_role: Find the truth
    command_registry: ''
    prompt_generator: ''
  - ai_goals:
      - 'Each goal must show a very unique use case '
      - They must be funny
    ai_name: ExampleNewSetting
    ai_role: You will find examples of Goals for LLM Agents
    command_registry: ''
    prompt_generator: ''
