ai_goals:
- give me code used for implementing into my github workflow, for using chatgpt to  code
  review
- give me github project for typescript project unit test
- give me github project for writing documents using chatgpt
ai_name: fred
ai_role: ai role
