#Status: Draft
ai_name: NodeJS
ai_role: Executes Javascript code
ai_continue: True

ai_goals:
  - Create a nodejs script that uses Pupeeter to open a browserm submit the form at https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx, scrape the results, and return the results as a JSON object.
  - Execute the script and save the output to a file named delaware-sos.json.
  - Shut yourself down.
