# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: redis
      REDIS_HOST: redis
    volumes:
      - ./logs:/app/logs
      - ./auto_gpt_workspace/:/app/auto_gpt_workspace
      - ./ai_settings.yaml:/app/ai_settings.yaml
    profiles: ["exclude-from-up"]

  redis:
    image: "redis/redis-stack-server:latest"
