# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis-stack
    build: ./
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]

  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    volumes:
      - ./redis-data:/data
      - ./redis-stack.conf:/redis-stack.conf
