# To boot the app run the following:
# docker compose run auto-gpt
# NOTE: Version 3.9 requires at least Docker Compose version 2 and Docker Engine version 20.10.13!

version: "3.9"

services:
  auto-gpt:
    build: ./
    env_file:
      - .env
    ports:
      - "8765:8765"
    environment:
      SUNCO_APP_ID: ${SUNCO_APP_ID}
      SUNCO_API_KEY: ${SUNCO_API_KEY}
      SUNCO_API_SECRET: ${SUNCO_API_SECRET}
      ZENDESK_API_TOKEN: ${ZENDESK_API_TOKEN}
      ZENDESK_SUBDOMAIN: ${ZENDESK_SUBDOMAIN}
      ZENDESK_EMAIL: ${ZENDESK_EMAIL}
      AUTO_GPT_WEBSOCKET_SERVER_HOST: ${AUTO_GPT_WEBSOCKET_SERVER_HOST:-0.0.0.0}
      AUTO_GPT_WEBSOCKET_SERVER_PORT: ${AUTO_GPT_WEBSOCKET_SERVER_PORT:-8765}
    volumes:
      - ./:/app
      - ./docker-compose.yml:/app/docker-compose.yml:ro
      - ./Dockerfile:/app/Dockerfile:ro
    profiles: ["exclude-from-up"]
