# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    volumes:
      - ./.env:/home/appuser/scripts/.env
    profiles: ["exclude-from-up"]

  redis:
    image: "redis/redis-stack-server:latest"
