[tool.poetry]
name = "autogpt_server"
version = "0.1.0"
description = ""
authors = [
    "SwiftyOS <craig.swift@agpt.co>",
    "Nicholas Tindle <nicholas.tindle@agpt.co>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
pydantic = "^2.7.1"
pytest = "^8.2.1"
uvicorn = { extras = ["standard"], version = "^0.30.1" }
fastapi = "^0.109.0"


[tool.poetry.group.dev.dependencies]
cx-freeze = "7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
app = "autogpt_server.app:main"


# [tool.cxfreeze]
# executables = [
#     { script = "autogpt_server/app.py", base = "console", target_name = "server" },
# ]

# [tool.cxfreeze.build_exe]
# excludes = []
# zip_include_packages = [
#     "encodings",
#     "multiprocessing",
#     "uvicorn",
#     "click",
#     "pydantic",
#     "fastapi",
#     "uvicorn.loops",
# ]

# # [tool.cxfreeze.bdist_msi]
# # extensions = [
# #     { "extension" = "txt", "verb" = "open", executable = "notepad.exe", context = "Edit with hello" },
# # ]

# [tool.cxfreeze.bdist_mac]
# # iconfile = 'icon.icns'
# bundle_name = 'AutoGPT'
# # plist_items = [["test", "test"], ["test2", "test2"]]
# include_resources = ['IMG_3775.jpeg']
