version: "3"
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: agpt_user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: agpt_local
      PGUSER: 5432
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: rnd/autogpt_server/Dockerfile
    environment:
      DATABASE_URL: "postgresql://agpt_user:pass123@postgres:5432/agpt_local"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: autogpt_builder/Dockerfile
      target: dev  # Use the dev target for development
    ports:
      - "3000:3000"
    environment:
      - AGPT_SERVER_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
