services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=agpt_user
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=agpt_local
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - app-network

  server_base:
    build:
      context: ../
      dockerfile: rnd/autogpt_server/Dockerfile
      target: server
    image: autogpt_server:latest
    command: ["echo", "This is a base image and should not be run directly"]

  migrate:
    image: autogpt_server:latest
    command: ["sh", "-c", "poetry run prisma migrate deploy"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://agpt_user:pass123@postgres:5432/agpt_local?connect_timeout=60
    networks:
      - app-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "poetry", "run", "prisma", "migrate", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    networks:
      - app-network

  rest_server:
    image: autogpt_server:latest
    command: ["poetry", "run", "rest"]
    develop:
      watch:
        - path: ./
          target: rnd/autogpt_server/
          action: rebuild
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - DATABASE_URL=postgresql://agpt_user:pass123@postgres:5432/agpt_local?connect_timeout=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - AUTH_ENABLED=false
      - PYRO_HOST=0.0.0.0
      - EXECUTIONMANAGER_HOST=executor
    ports:
      - "8006:8000"
      - "8003:8003" # execution scheduler
    networks:
      - app-network

  executor:
    image: autogpt_server:latest
    command: ["poetry", "run", "executor"]
    develop:
      watch:
        - path: ./
          target: rnd/autogpt_server/
          action: rebuild
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      migrate:
        condition: service_started
    environment:
      - SUPABASE_URL=http://localhost:54321
      - SUPABASE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - DATABASE_URL=postgresql://agpt_user:pass123@postgres:5432/agpt_local?connect_timeout=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - ENABLE_AUTH=true
      - PYRO_HOST=0.0.0.0
      - AGENTSERVER_HOST=rest_server
    ports:
      - "8002:8000"
    networks:
      - app-network

  websocket_server:
    image: autogpt_server:latest
    command: ["poetry", "run", "ws"]
    develop:
      watch:
        - path: ./
          target: rnd/autogpt_server/
          action: rebuild
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    environment:
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - DATABASE_URL=postgresql://agpt_user:pass123@postgres:5432/agpt_local?connect_timeout=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - ENABLE_AUTH=true
      - PYRO_HOST=0.0.0.0
    ports:
      - "8001:8000"
    networks:
      - app-network

  market:
    build:
      context: ../
      dockerfile: rnd/market/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - DATABASE_URL=postgresql://agpt_user:pass123@postgres:5432/agpt_local?connect_timeout=60
    ports:
      - "8015:8015"
    networks:
      - app-network

  frontend:
    build:
      context: ../
      dockerfile: rnd/autogpt_builder/Dockerfile
      target: dev
    depends_on:
      postgres:
        condition: service_healthy
      rest_server:
        condition: service_started
      websocket_server:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://kong:8000
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - DATABASE_URL=postgresql://agpt_user:pass123@postgres:5432/agpt_local?connect_timeout=60
      - NEXT_PUBLIC_AGPT_SERVER_URL=http://localhost:8006/api
      - NEXT_PUBLIC_AGPT_WS_SERVER_URL=ws://localhost:8001/ws
      - NEXT_PUBLIC_AGPT_MARKETPLACE_URL=http://localhost:8015/api/v1/market
    ports:
      - "3000:3000"
    networks:
      - app-network

  mail:
    container_name: inbucket
    image: inbucket/inbucket:latest
    ports:
      - "9000:9000"
networks:
  app-network:
    driver: bridge