name: Bug report 🐛
description: Create a bug report for Auto-GPT.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Before you continue
        * Check out our [backlog], [roadmap] and join our [discord] to discuss what's going on
        * If you need help, you can ask in the [discussions] section or in [#tech-support]
        * **Thoroughly search the [existing issues] before creating a new one**
        * Read our [wiki page on Contributing]
        [backlog]: https://github.com/orgs/Significant-Gravitas/projects/1
        [roadmap]: https://github.com/orgs/Significant-Gravitas/projects/2  
        [discord]: https://discord.gg/autogpt
        [discussions]: https://github.com/Significant-Gravitas/Auto-GPT/discussions
        [#tech-support]: https://discord.com/channels/1092243196446249134/1092275629602394184
        [existing issues]: https://github.com/Significant-Gravitas/Auto-GPT/issues?q=is%3Aissue
        [wiki page on Contributing]: https://github.com/Significant-Gravitas/Auto-GPT/wiki/Contributing

  - type: checkboxes
    attributes:
      label: ⚠️ Search for existing issues first ⚠️
      description: >
        Please [search the history](https://github.com/Torantulino/Auto-GPT/issues)
        to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues, and there is no existing issue for my problem
          required: true

  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.
        ⚠️ SUPER-busy repo, please help the volunteer maintainers.
        The less time we spend here, the more time we spend building AutoGPT.
        
        Please help us help you:
        - Does it work on `stable` branch (https://github.com/Torantulino/Auto-GPT/tree/stable)?
        - Does it work on current `master` (https://github.com/Torantulino/Auto-GPT/tree/master)?
        - Search for existing issues, "add comment" is tidier than "new issue" and newer issues will not be reviewed earlier, 
          this is dependent on the current priorities set by our wonderful team
        - Ask on our Discord (https://discord.gg/autogpt)
        - Provide relevant info:
          - Provide commit-hash (`git rev-parse HEAD` gets it)
          - If it's a pip/packages issue, provide pip version, python version
          - If it's a crash, provide traceback.

  - type: dropdown
    attributes:
      label: Which Operating System are you using?
      description: >
        Please select the operating system you were using to run Auto-GPT when this problem occurred.
      options:
        - Windows
        - Linux
        - MacOS
        - Docker
        - Devcontainer / Codespace
        - Windows Subsystem for Linux (WSL)
        - Other
    validations:
      required: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the system
            description: Please specify the system you are working on.

  - type: dropdown
    attributes:
      label: Which version of Auto-GPT are you using?
      description: |
        Please select which version of Auto-GPT you were using when this issue occurred.
        If you downloaded the code from the [releases page](https://github.com/Significant-Gravitas/Auto-GPT/releases/) make sure you were using the latest code. 
        **If you weren't please try with the [latest code](https://github.com/Significant-Gravitas/Auto-GPT/releases/)**.
        If installed with git you can run `git branch` to see which version of Auto-GPT you are running.
      options:
        - Latest Release
        - Stable (branch)
        - Master (branch)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Do you use OpenAI GPT-3 or GPT-4?
      description: >
        If you are using Auto-GPT with `--gpt3only`, your problems may be caused by
        the [limitations](https://github.com/Significant-Gravitas/Auto-GPT/issues?q=is%3Aissue+label%3A%22AI+model+limitation%22) of GPT-3.5.
      options:
        - GPT-3.5
        - GPT-4
        - GPT-4(32k)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Which area covers your issue best?
      description: >
        Select the area related to the issue you are reporting.
      options:
        - Installation
        - Setup
        - Memory
        - Performance
        - Prompt
        - Commands
        - Plugins
        - AI Model Limitations
        - Challenges
        - Other
    validations:
      required: true
      autolabels: true
      nested_fields:
        - type: text
          attributes:
            label: Specify the area
            description: Please specify the area you think is best related to the issue.

  - type: textarea
    attributes:
      label: Describe your issue.
      description: Describe the problem you are experiencing. Try to describe only the issue and phrase it short but clear. ⚠️ Provide NO other data in this field  

  #Following are optional file uploads with logs
  - type: markdown
    attributes:
      value: |
        "The following is optional, please keep in mind that the log files may contain 
        personal information such as credentials.
        
        The log files are located in the folder 'logs' inside the main auto-gpt folder."
        
  - type: file
    attributes:
      label: Upload Activity Log
      description: |
        Upload the activity log, this can help us understand the issue better. 
        ⚠️ The activity log may contain personal data given to auto-gpt by you in prompt or input as well as 
        any personal information that auto-gpt collected out of files during last run. Do not add the activity log if you are not comfortable with sharing it. ⚠️
    validations:
      required: false

  - type: file
    attributes:
      label: Upload Error Log
      description: |
        Upload the error log, this will help us understand the issue better. 
        ⚠️ The error log may contain personal data given to auto-gpt by you in prompt or input as well as 
        any personal information that auto-gpt collected out of files during last run. Do not add the activity log if you are not comfortable with sharing it. ⚠️
    validations:
      required: false

