apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "autogpt-market.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ .Release.Name }}-secrets
      namespace: {{ .Release.Namespace }}