# dev values, overwrite base values as needed.

image:
  repository: us-east1-docker.pkg.dev/agpt-dev/agpt-frontend-dev/agpt-frontend-dev
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "dev-agpt-builder-sa@agpt-dev.iam.gserviceaccount.com"
  name: "dev-agpt-builder-sa"

service:
  type: ClusterIP
  port: 8000
  targetPort: 3000
  annotations:
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "agpt-dev-agpt-builder-ip"
    networking.gke.io/managed-certificates: "autogpt-builder-cert"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/v1beta1.FrontendConfig: "autogpt-builder-frontend-config"
  hosts:
    - host: dev-builder.agpt.co
      paths:
        - path: /
          pathType: Prefix
      backend:
        service:
          name: autogpt-builder
          port: 8000
  defaultBackend:
    service:
      name: autogpt-builder
      port:
        number: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe: null
readinessProbe: null

domain: "dev-builder.agpt.co"
wwwDomain: "www.dev-builder.agpt.co"


env:
  APP_ENV: "dev"
  NEXT_PUBLIC_AGPT_SERVER_URL: "https://dev-server.agpt.co/api"
  NEXT_PUBLIC_SUPABASE_URL: "https://adfjtextkuilwuhzdjpf.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZmp0ZXh0a3VpbHd1aHpkanBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAyNTE3MDIsImV4cCI6MjA0NTgyNzcwMn0.IuQNXsHEKJNxtS9nyFeqO0BGMYN8sPiObQhuJLSK9xk"
  NEXT_PUBLIC_AUTH_CALLBACK_URL: "https://dev-server.agpt.co/auth/callback"
  NEXT_PUBLIC_AGPT_WS_SERVER_URL: "wss://dev-ws-server.agpt.co/ws"
  NEXT_PUBLIC_AGPT_MARKETPLACE_URL: "https://dev-market.agpt.co/api/v1/market"
  NEXT_PUBLIC_BEHAVE_AS: "CLOUD"

secrets:
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
