name: Merge and Commit Cassettes

on:
  pull_request_target:
    types:
      - closed

jobs:
  update-cassettes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This is necessary to fetch all branches and tags

      - name: Fetch all branches
        run: git fetch --all

      - name: Create PR
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update cassettes
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: cassette-pr-${{ github.event.pull_request.number }}
          delete-branch: false
          title: "Update cassettes"
          body: "This PR updates the cassettes."
          draft: false

      - name: Check PR
        run: |
          echo "Pull Request Number - ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"
