name: 'AFAAS Changelog CI v2'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
        - name: "Build Changelog"
          uses: mikepenz/release-changelog-builder-action@v4.1.0
          with:
            configurationJson: |
                {
                "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
                "pr_template": "[#{{NUMBER}}](#{{URL}}) - #{{TITLE}} - [@#{{AUTHOR}}](https://github.com/#{{AUTHOR}})
                ) , #{{LABELS}} \n",
                "categories": [
                    {
                        "title": "## 💬 Other",
                        "labels": ["other"]
                    },
                    {
                        "title": "## 📦 Dependencies",
                        "labels": ["dependencies"]
                    }
                ],
                "custom_placeholders": [
                  {
                    "name": "SMILEY",
                    "source": "LABELS",
                    "transformer": {
                      "pattern": "[\\S\\s]*?(https:\\/\\/corp\\.atlassian\\.net\\/browse\\/LABELS-.{2,4})[\\S\\s]*",
                      "target": "- $1"
                    }
                  }
                ]
                }
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}