name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      continue-on-error: false
      run: python -m flake8 . --ignore E266,E402,E501,E722,W503,W504,F

    - name: Run unittest tests with coverage
      run: |
        pytest --cov=autogpt --without-integration --without-slow-integration

    - name: Generate coverage report
      run: |
        coverage report
        coverage xml
