name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Lint with flake8
      continue-on-error: false
      run: poetry run flake8 autogpt/ tests/ --select E303,W293,W291,W292,E305,E231,E302

    - name: Run unittest tests with coverage
      run: |
        poetry run coverage run --source=autogpt -m unittest discover tests

    - name: Generate coverage report
      run: |
        poetry run coverage report
        poetry run coverage xml
