name: Test and Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=`make image-tag`
          IMAGE_URL=`make image-url`
          echo "Building Docker image: $IMAGE_URL"
          make image
          docker save $IMAGE_URL > image.tar
          echo "image-url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Cache docker image
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: docker-image.tar
          key: test-image-${{ steps.build.outputs.image-url }}

  pytest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run pytest
        uses: ./.github/actions/run-docker
        with:
          image-url: ${{ needs.build.outputs.image-url }}
          command: make pytest

  black:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run black
        uses: ./.github/actions/run-docker
        with:
          image-url: ${{ needs.build.outputs.image-url }}
          command: make black-check

  flake8:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run flake8
        uses: ./.github/actions/run-docker
        with:
          image-url: ${{ needs.build.outputs.image-url }}
          command: make flake8
