name: Test and Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

env:
  DOCKER_REPOSITORY: "ghcr.io/auto-gpt/sandbox"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=make get-image-tag
          IMAGE_URL=make get-image-url
          echo "Building Docker image with tag: $IMAGE_URL"
          make image
          docker save -o image.tar test-image

  pytest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Load Image from Build Job
        uses: docker/load-action@v2
        with:
          input: ${{ needs.build.outputs.test-image }}
      - name: Run pytest
        uses: ./actions/docker/run-docker
        with:
          image-tag: ${{ needs.build.outputs.image-tag }}
          command: make pytest

  black:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Load Image from Build Job
        uses: docker/load-action@v2
        with:
          input: ${{ needs.build.outputs.test-image }}

      - name: Run black
        uses: ./actions/docker/run-docker
        with:
          image-tag: ${{ needs.build.outputs.image-tag }}
          command: make black-check

  flake8:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Load Image from Build Job
        uses: docker/load-action@v2
        with:
          input: ${{ needs.build.outputs.test-image }}

      - name: Run flake8
        uses: ./actions/docker/run-docker
        with:
          image-tag: ${{ needs.build.outputs.image-tag }}
          command: make flake8
