name: Test and Lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

env:
  DOCKER_REPOSITORY: "ghcr.io/auto-gpt/sandbox"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=`make image-tag`
          IMAGE_URL=`make image-url`
          echo "Building Docker image with tag: $IMAGE_URL"
          make image
          docker save -o image.tar $IMAGE_URL
          docker save $IMAGE_URL > image.tar

      - name: Cache docker image
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: docker-image.tar
          key: test-image

  pytest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cache docker image
        uses: actions/cache@v2
        with:
          path: docker-image.tar
          key: test-image
      - name: Run pytest
        uses: ./.github/actions/run-docker
        with:
          image-tag: ${{ needs.build.outputs.image-tag }}
          command: make pytest

  black:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cache docker image
        uses: actions/cache@v2
        with:
          path: docker-image.tar
          key: test-image
      - name: Run black
        uses: ./.github/actions/run-docker
        with:
          image-tag: ${{ needs.build.outputs.image-tag }}
          command: make black-check

  flake8:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run flake8
        uses: ./.github/actions/run-docker
        with:
          image-tag: ${{ needs.build.outputs.image-tag }}
          command: make flake8
